version: "3.8"

services:

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    restart: always
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094

  mongodb:
    container_name: "scheduler-mongodb"
    image: mongo:6.0
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  postgres-db:
    image: postgres:15
    container_name: "postgres-db-container"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scheduler
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb_data_container:
  postgres_data:
